language: node_js
node_js:
  - 8
  - 10
  - node
  - '8'
  - '10'
  - '12'
os:
  - linux
  - windows
install:
  - npm ci
script:
  - npm run lint
  - npm run build
  - npm test
notifications:
  email: false
